//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ETrains.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbTrainEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbTrainEntities object using the connection string found in the 'dbTrainEntities' section of the application configuration file.
        /// </summary>
        public dbTrainEntities() : base("name=dbTrainEntities", "dbTrainEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbTrainEntities object.
        /// </summary>
        public dbTrainEntities(string connectionString) : base(connectionString, "dbTrainEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbTrainEntities object.
        /// </summary>
        public dbTrainEntities(EntityConnection connection) : base(connection, "dbTrainEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCompany> tblCompanies
        {
            get
            {
                if ((_tblCompanies == null))
                {
                    _tblCompanies = base.CreateObjectSet<tblCompany>("tblCompanies");
                }
                return _tblCompanies;
            }
        }
        private ObjectSet<tblCompany> _tblCompanies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCustom> tblCustoms
        {
            get
            {
                if ((_tblCustoms == null))
                {
                    _tblCustoms = base.CreateObjectSet<tblCustom>("tblCustoms");
                }
                return _tblCustoms;
            }
        }
        private ObjectSet<tblCustom> _tblCustoms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblToaTau> tblToaTaus
        {
            get
            {
                if ((_tblToaTaus == null))
                {
                    _tblToaTaus = base.CreateObjectSet<tblToaTau>("tblToaTaus");
                }
                return _tblToaTaus;
            }
        }
        private ObjectSet<tblToaTau> _tblToaTaus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblToKhaiTau> tblToKhaiTaus
        {
            get
            {
                if ((_tblToKhaiTaus == null))
                {
                    _tblToKhaiTaus = base.CreateObjectSet<tblToKhaiTau>("tblToKhaiTaus");
                }
                return _tblToKhaiTaus;
            }
        }
        private ObjectSet<tblToKhaiTau> _tblToKhaiTaus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTrain> tblTrains
        {
            get
            {
                if ((_tblTrains == null))
                {
                    _tblTrains = base.CreateObjectSet<tblTrain>("tblTrains");
                }
                return _tblTrains;
            }
        }
        private ObjectSet<tblTrain> _tblTrains;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblType> tblTypes
        {
            get
            {
                if ((_tblTypes == null))
                {
                    _tblTypes = base.CreateObjectSet<tblType>("tblTypes");
                }
                return _tblTypes;
            }
        }
        private ObjectSet<tblType> _tblTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUser> tblUsers
        {
            get
            {
                if ((_tblUsers == null))
                {
                    _tblUsers = base.CreateObjectSet<tblUser>("tblUsers");
                }
                return _tblUsers;
            }
        }
        private ObjectSet<tblUser> _tblUsers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ViewGetCurrentDate> ViewGetCurrentDates
        {
            get
            {
                if ((_ViewGetCurrentDates == null))
                {
                    _ViewGetCurrentDates = base.CreateObjectSet<ViewGetCurrentDate>("ViewGetCurrentDates");
                }
                return _ViewGetCurrentDates;
            }
        }
        private ObjectSet<ViewGetCurrentDate> _ViewGetCurrentDates;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCompanies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCompanies(tblCompany tblCompany)
        {
            base.AddObject("tblCompanies", tblCompany);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCustoms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCustoms(tblCustom tblCustom)
        {
            base.AddObject("tblCustoms", tblCustom);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblToaTaus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblToaTaus(tblToaTau tblToaTau)
        {
            base.AddObject("tblToaTaus", tblToaTau);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblToKhaiTaus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblToKhaiTaus(tblToKhaiTau tblToKhaiTau)
        {
            base.AddObject("tblToKhaiTaus", tblToKhaiTau);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTrains EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTrains(tblTrain tblTrain)
        {
            base.AddObject("tblTrains", tblTrain);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTypes(tblType tblType)
        {
            base.AddObject("tblTypes", tblType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUsers(tblUser tblUser)
        {
            base.AddObject("tblUsers", tblUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ViewGetCurrentDates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToViewGetCurrentDates(ViewGetCurrentDate viewGetCurrentDate)
        {
            base.AddObject("ViewGetCurrentDates", viewGetCurrentDate);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTrainModel", Name="tblCompany")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCompany : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCompany object.
        /// </summary>
        /// <param name="companyCode">Initial value of the CompanyCode property.</param>
        public static tblCompany CreatetblCompany(global::System.String companyCode)
        {
            tblCompany tblCompany = new tblCompany();
            tblCompany.CompanyCode = companyCode;
            return tblCompany;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyCode
        {
            get
            {
                return _CompanyCode;
            }
            set
            {
                if (_CompanyCode != value)
                {
                    OnCompanyCodeChanging(value);
                    ReportPropertyChanging("CompanyCode");
                    _CompanyCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CompanyCode");
                    OnCompanyCodeChanged();
                }
            }
        }
        private global::System.String _CompanyCode;
        partial void OnCompanyCodeChanging(global::System.String value);
        partial void OnCompanyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                OnCompanyNameChanging(value);
                ReportPropertyChanging("CompanyName");
                _CompanyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyName");
                OnCompanyNameChanged();
            }
        }
        private global::System.String _CompanyName;
        partial void OnCompanyNameChanging(global::System.String value);
        partial void OnCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Int32> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifiedBy;
        partial void OnModifiedByChanging(Nullable<global::System.Int32> value);
        partial void OnModifiedByChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTrainModel", Name="tblCustom")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCustom : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCustom object.
        /// </summary>
        /// <param name="customsCode">Initial value of the CustomsCode property.</param>
        public static tblCustom CreatetblCustom(global::System.String customsCode)
        {
            tblCustom tblCustom = new tblCustom();
            tblCustom.CustomsCode = customsCode;
            return tblCustom;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomsCode
        {
            get
            {
                return _CustomsCode;
            }
            set
            {
                if (_CustomsCode != value)
                {
                    OnCustomsCodeChanging(value);
                    ReportPropertyChanging("CustomsCode");
                    _CustomsCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CustomsCode");
                    OnCustomsCodeChanged();
                }
            }
        }
        private global::System.String _CustomsCode;
        partial void OnCustomsCodeChanging(global::System.String value);
        partial void OnCustomsCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomsName
        {
            get
            {
                return _CustomsName;
            }
            set
            {
                OnCustomsNameChanging(value);
                ReportPropertyChanging("CustomsName");
                _CustomsName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomsName");
                OnCustomsNameChanged();
            }
        }
        private global::System.String _CustomsName;
        partial void OnCustomsNameChanging(global::System.String value);
        partial void OnCustomsNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Int32> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifiedBy;
        partial void OnModifiedByChanging(Nullable<global::System.Int32> value);
        partial void OnModifiedByChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTrainModel", Name="tblToaTau")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblToaTau : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblToaTau object.
        /// </summary>
        /// <param name="toaTauID">Initial value of the ToaTauID property.</param>
        /// <param name="trainID">Initial value of the TrainID property.</param>
        public static tblToaTau CreatetblToaTau(global::System.Int64 toaTauID, global::System.Int64 trainID)
        {
            tblToaTau tblToaTau = new tblToaTau();
            tblToaTau.ToaTauID = toaTauID;
            tblToaTau.TrainID = trainID;
            return tblToaTau;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ToaTauID
        {
            get
            {
                return _ToaTauID;
            }
            set
            {
                if (_ToaTauID != value)
                {
                    OnToaTauIDChanging(value);
                    ReportPropertyChanging("ToaTauID");
                    _ToaTauID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ToaTauID");
                    OnToaTauIDChanged();
                }
            }
        }
        private global::System.Int64 _ToaTauID;
        partial void OnToaTauIDChanging(global::System.Int64 value);
        partial void OnToaTauIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ma_ToaTau
        {
            get
            {
                return _Ma_ToaTau;
            }
            set
            {
                OnMa_ToaTauChanging(value);
                ReportPropertyChanging("Ma_ToaTau");
                _Ma_ToaTau = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ma_ToaTau");
                OnMa_ToaTauChanged();
            }
        }
        private global::System.String _Ma_ToaTau;
        partial void OnMa_ToaTauChanging(global::System.String value);
        partial void OnMa_ToaTauChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String So_VanTai_Don
        {
            get
            {
                return _So_VanTai_Don;
            }
            set
            {
                OnSo_VanTai_DonChanging(value);
                ReportPropertyChanging("So_VanTai_Don");
                _So_VanTai_Don = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("So_VanTai_Don");
                OnSo_VanTai_DonChanged();
            }
        }
        private global::System.String _So_VanTai_Don;
        partial void OnSo_VanTai_DonChanging(global::System.String value);
        partial void OnSo_VanTai_DonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Ngay_VanTai_Don
        {
            get
            {
                return _Ngay_VanTai_Don;
            }
            set
            {
                OnNgay_VanTai_DonChanging(value);
                ReportPropertyChanging("Ngay_VanTai_Don");
                _Ngay_VanTai_Don = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ngay_VanTai_Don");
                OnNgay_VanTai_DonChanged();
            }
        }
        private Nullable<global::System.DateTime> _Ngay_VanTai_Don;
        partial void OnNgay_VanTai_DonChanging(Nullable<global::System.DateTime> value);
        partial void OnNgay_VanTai_DonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ten_DoiTac
        {
            get
            {
                return _Ten_DoiTac;
            }
            set
            {
                OnTen_DoiTacChanging(value);
                ReportPropertyChanging("Ten_DoiTac");
                _Ten_DoiTac = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ten_DoiTac");
                OnTen_DoiTacChanged();
            }
        }
        private global::System.String _Ten_DoiTac;
        partial void OnTen_DoiTacChanging(global::System.String value);
        partial void OnTen_DoiTacChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ma_DoanhNghiep
        {
            get
            {
                return _Ma_DoanhNghiep;
            }
            set
            {
                OnMa_DoanhNghiepChanging(value);
                ReportPropertyChanging("Ma_DoanhNghiep");
                _Ma_DoanhNghiep = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ma_DoanhNghiep");
                OnMa_DoanhNghiepChanged();
            }
        }
        private global::System.String _Ma_DoanhNghiep;
        partial void OnMa_DoanhNghiepChanging(global::System.String value);
        partial void OnMa_DoanhNghiepChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ten_Hang
        {
            get
            {
                return _Ten_Hang;
            }
            set
            {
                OnTen_HangChanging(value);
                ReportPropertyChanging("Ten_Hang");
                _Ten_Hang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ten_Hang");
                OnTen_HangChanged();
            }
        }
        private global::System.String _Ten_Hang;
        partial void OnTen_HangChanging(global::System.String value);
        partial void OnTen_HangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Trong_Luong
        {
            get
            {
                return _Trong_Luong;
            }
            set
            {
                OnTrong_LuongChanging(value);
                ReportPropertyChanging("Trong_Luong");
                _Trong_Luong = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Trong_Luong");
                OnTrong_LuongChanged();
            }
        }
        private global::System.String _Trong_Luong;
        partial void OnTrong_LuongChanging(global::System.String value);
        partial void OnTrong_LuongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Don_Vi_Tinh
        {
            get
            {
                return _Don_Vi_Tinh;
            }
            set
            {
                OnDon_Vi_TinhChanging(value);
                ReportPropertyChanging("Don_Vi_Tinh");
                _Don_Vi_Tinh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Don_Vi_Tinh");
                OnDon_Vi_TinhChanged();
            }
        }
        private global::System.String _Don_Vi_Tinh;
        partial void OnDon_Vi_TinhChanging(global::System.String value);
        partial void OnDon_Vi_TinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Seal_VanTai
        {
            get
            {
                return _Seal_VanTai;
            }
            set
            {
                OnSeal_VanTaiChanging(value);
                ReportPropertyChanging("Seal_VanTai");
                _Seal_VanTai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Seal_VanTai");
                OnSeal_VanTaiChanged();
            }
        }
        private global::System.String _Seal_VanTai;
        partial void OnSeal_VanTaiChanging(global::System.String value);
        partial void OnSeal_VanTaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Seal_HaiQuan
        {
            get
            {
                return _Seal_HaiQuan;
            }
            set
            {
                OnSeal_HaiQuanChanging(value);
                ReportPropertyChanging("Seal_HaiQuan");
                _Seal_HaiQuan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Seal_HaiQuan");
                OnSeal_HaiQuanChanged();
            }
        }
        private global::System.String _Seal_HaiQuan;
        partial void OnSeal_HaiQuanChanging(global::System.String value);
        partial void OnSeal_HaiQuanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ghi_Chu
        {
            get
            {
                return _Ghi_Chu;
            }
            set
            {
                OnGhi_ChuChanging(value);
                ReportPropertyChanging("Ghi_Chu");
                _Ghi_Chu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ghi_Chu");
                OnGhi_ChuChanged();
            }
        }
        private global::System.String _Ghi_Chu;
        partial void OnGhi_ChuChanging(global::System.String value);
        partial void OnGhi_ChuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Int32> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifiedBy;
        partial void OnModifiedByChanging(Nullable<global::System.Int32> value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TrainID
        {
            get
            {
                return _TrainID;
            }
            set
            {
                if (_TrainID != value)
                {
                    OnTrainIDChanging(value);
                    ReportPropertyChanging("TrainID");
                    _TrainID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TrainID");
                    OnTrainIDChanged();
                }
            }
        }
        private global::System.Int64 _TrainID;
        partial void OnTrainIDChanging(global::System.Int64 value);
        partial void OnTrainIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTrainModel", Name="tblToKhaiTau")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblToKhaiTau : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblToKhaiTau object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="trainID">Initial value of the TrainID property.</param>
        public static tblToKhaiTau CreatetblToKhaiTau(global::System.Int64 id, global::System.Int64 trainID)
        {
            tblToKhaiTau tblToKhaiTau = new tblToKhaiTau();
            tblToKhaiTau.ID = id;
            tblToKhaiTau.TrainID = trainID;
            return tblToKhaiTau;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _Number;
        partial void OnNumberChanging(Nullable<global::System.Int32> value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateDeclaration
        {
            get
            {
                return _DateDeclaration;
            }
            set
            {
                OnDateDeclarationChanging(value);
                ReportPropertyChanging("DateDeclaration");
                _DateDeclaration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateDeclaration");
                OnDateDeclarationChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateDeclaration;
        partial void OnDateDeclarationChanging(Nullable<global::System.DateTime> value);
        partial void OnDateDeclarationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TypeCode
        {
            get
            {
                return _TypeCode;
            }
            set
            {
                OnTypeCodeChanging(value);
                ReportPropertyChanging("TypeCode");
                _TypeCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TypeCode");
                OnTypeCodeChanged();
            }
        }
        private global::System.String _TypeCode;
        partial void OnTypeCodeChanging(global::System.String value);
        partial void OnTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomCode
        {
            get
            {
                return _CustomCode;
            }
            set
            {
                OnCustomCodeChanging(value);
                ReportPropertyChanging("CustomCode");
                _CustomCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomCode");
                OnCustomCodeChanged();
            }
        }
        private global::System.String _CustomCode;
        partial void OnCustomCodeChanging(global::System.String value);
        partial void OnCustomCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyCode
        {
            get
            {
                return _CompanyCode;
            }
            set
            {
                OnCompanyCodeChanging(value);
                ReportPropertyChanging("CompanyCode");
                _CompanyCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyCode");
                OnCompanyCodeChanged();
            }
        }
        private global::System.String _CompanyCode;
        partial void OnCompanyCodeChanging(global::System.String value);
        partial void OnCompanyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Int32> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifiedBy;
        partial void OnModifiedByChanging(Nullable<global::System.Int32> value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TrainID
        {
            get
            {
                return _TrainID;
            }
            set
            {
                if (_TrainID != value)
                {
                    OnTrainIDChanging(value);
                    ReportPropertyChanging("TrainID");
                    _TrainID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TrainID");
                    OnTrainIDChanged();
                }
            }
        }
        private global::System.Int64 _TrainID;
        partial void OnTrainIDChanging(global::System.Int64 value);
        partial void OnTrainIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTrainModel", Name="tblTrain")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTrain : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTrain object.
        /// </summary>
        /// <param name="trainID">Initial value of the TrainID property.</param>
        public static tblTrain CreatetblTrain(global::System.Int64 trainID)
        {
            tblTrain tblTrain = new tblTrain();
            tblTrain.TrainID = trainID;
            return tblTrain;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TrainID
        {
            get
            {
                return _TrainID;
            }
            set
            {
                if (_TrainID != value)
                {
                    OnTrainIDChanging(value);
                    ReportPropertyChanging("TrainID");
                    _TrainID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TrainID");
                    OnTrainIDChanged();
                }
            }
        }
        private global::System.Int64 _TrainID;
        partial void OnTrainIDChanging(global::System.Int64 value);
        partial void OnTrainIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.String _Number;
        partial void OnNumberChanging(global::System.String value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int16> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int16> value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsImport
        {
            get
            {
                return _IsImport;
            }
            set
            {
                OnIsImportChanging(value);
                ReportPropertyChanging("IsImport");
                _IsImport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsImport");
                OnIsImportChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsImport;
        partial void OnIsImportChanging(Nullable<global::System.Boolean> value);
        partial void OnIsImportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateImport
        {
            get
            {
                return _DateImport;
            }
            set
            {
                OnDateImportChanging(value);
                ReportPropertyChanging("DateImport");
                _DateImport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateImport");
                OnDateImportChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateImport;
        partial void OnDateImportChanging(Nullable<global::System.DateTime> value);
        partial void OnDateImportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsExport
        {
            get
            {
                return _IsExport;
            }
            set
            {
                OnIsExportChanging(value);
                ReportPropertyChanging("IsExport");
                _IsExport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsExport");
                OnIsExportChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsExport;
        partial void OnIsExportChanging(Nullable<global::System.Boolean> value);
        partial void OnIsExportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateExport
        {
            get
            {
                return _DateExport;
            }
            set
            {
                OnDateExportChanging(value);
                ReportPropertyChanging("DateExport");
                _DateExport = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateExport");
                OnDateExportChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateExport;
        partial void OnDateExportChanging(Nullable<global::System.DateTime> value);
        partial void OnDateExportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumberHandover
        {
            get
            {
                return _NumberHandover;
            }
            set
            {
                OnNumberHandoverChanging(value);
                ReportPropertyChanging("NumberHandover");
                _NumberHandover = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumberHandover");
                OnNumberHandoverChanged();
            }
        }
        private global::System.String _NumberHandover;
        partial void OnNumberHandoverChanging(global::System.String value);
        partial void OnNumberHandoverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateHandover
        {
            get
            {
                return _DateHandover;
            }
            set
            {
                OnDateHandoverChanging(value);
                ReportPropertyChanging("DateHandover");
                _DateHandover = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateHandover");
                OnDateHandoverChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateHandover;
        partial void OnDateHandoverChanging(Nullable<global::System.DateTime> value);
        partial void OnDateHandoverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodeStation
        {
            get
            {
                return _CodeStation;
            }
            set
            {
                OnCodeStationChanging(value);
                ReportPropertyChanging("CodeStation");
                _CodeStation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodeStation");
                OnCodeStationChanged();
            }
        }
        private global::System.String _CodeStation;
        partial void OnCodeStationChanging(global::System.String value);
        partial void OnCodeStationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodeStationFromTo
        {
            get
            {
                return _CodeStationFromTo;
            }
            set
            {
                OnCodeStationFromToChanging(value);
                ReportPropertyChanging("CodeStationFromTo");
                _CodeStationFromTo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodeStationFromTo");
                OnCodeStationFromToChanged();
            }
        }
        private global::System.String _CodeStationFromTo;
        partial void OnCodeStationFromToChanging(global::System.String value);
        partial void OnCodeStationFromToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StatusVehicle
        {
            get
            {
                return _StatusVehicle;
            }
            set
            {
                OnStatusVehicleChanging(value);
                ReportPropertyChanging("StatusVehicle");
                _StatusVehicle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StatusVehicle");
                OnStatusVehicleChanged();
            }
        }
        private global::System.String _StatusVehicle;
        partial void OnStatusVehicleChanging(global::System.String value);
        partial void OnStatusVehicleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StatusGoods
        {
            get
            {
                return _StatusGoods;
            }
            set
            {
                OnStatusGoodsChanging(value);
                ReportPropertyChanging("StatusGoods");
                _StatusGoods = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StatusGoods");
                OnStatusGoodsChanged();
            }
        }
        private global::System.String _StatusGoods;
        partial void OnStatusGoodsChanging(global::System.String value);
        partial void OnStatusGoodsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumberPartTrain
        {
            get
            {
                return _NumberPartTrain;
            }
            set
            {
                OnNumberPartTrainChanging(value);
                ReportPropertyChanging("NumberPartTrain");
                _NumberPartTrain = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumberPartTrain");
                OnNumberPartTrainChanged();
            }
        }
        private global::System.String _NumberPartTrain;
        partial void OnNumberPartTrainChanging(global::System.String value);
        partial void OnNumberPartTrainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Jounery
        {
            get
            {
                return _Jounery;
            }
            set
            {
                OnJouneryChanging(value);
                ReportPropertyChanging("Jounery");
                _Jounery = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Jounery");
                OnJouneryChanged();
            }
        }
        private global::System.String _Jounery;
        partial void OnJouneryChanging(global::System.String value);
        partial void OnJouneryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PassengerVN
        {
            get
            {
                return _PassengerVN;
            }
            set
            {
                OnPassengerVNChanging(value);
                ReportPropertyChanging("PassengerVN");
                _PassengerVN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PassengerVN");
                OnPassengerVNChanged();
            }
        }
        private Nullable<global::System.Int32> _PassengerVN;
        partial void OnPassengerVNChanging(Nullable<global::System.Int32> value);
        partial void OnPassengerVNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PassengerForegin
        {
            get
            {
                return _PassengerForegin;
            }
            set
            {
                OnPassengerForeginChanging(value);
                ReportPropertyChanging("PassengerForegin");
                _PassengerForegin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PassengerForegin");
                OnPassengerForeginChanged();
            }
        }
        private Nullable<global::System.Int32> _PassengerForegin;
        partial void OnPassengerForeginChanging(Nullable<global::System.Int32> value);
        partial void OnPassengerForeginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Staff
        {
            get
            {
                return _Staff;
            }
            set
            {
                OnStaffChanging(value);
                ReportPropertyChanging("Staff");
                _Staff = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Staff");
                OnStaffChanged();
            }
        }
        private Nullable<global::System.Int32> _Staff;
        partial void OnStaffChanging(Nullable<global::System.Int32> value);
        partial void OnStaffChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Int32> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifiedBy;
        partial void OnModifiedByChanging(Nullable<global::System.Int32> value);
        partial void OnModifiedByChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTrainModel", Name="tblType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblType object.
        /// </summary>
        /// <param name="typeCode">Initial value of the TypeCode property.</param>
        public static tblType CreatetblType(global::System.String typeCode)
        {
            tblType tblType = new tblType();
            tblType.TypeCode = typeCode;
            return tblType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TypeCode
        {
            get
            {
                return _TypeCode;
            }
            set
            {
                if (_TypeCode != value)
                {
                    OnTypeCodeChanging(value);
                    ReportPropertyChanging("TypeCode");
                    _TypeCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TypeCode");
                    OnTypeCodeChanged();
                }
            }
        }
        private global::System.String _TypeCode;
        partial void OnTypeCodeChanging(global::System.String value);
        partial void OnTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TypeName
        {
            get
            {
                return _TypeName;
            }
            set
            {
                OnTypeNameChanging(value);
                ReportPropertyChanging("TypeName");
                _TypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TypeName");
                OnTypeNameChanged();
            }
        }
        private global::System.String _TypeName;
        partial void OnTypeNameChanging(global::System.String value);
        partial void OnTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Int32> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifiedBy;
        partial void OnModifiedByChanging(Nullable<global::System.Int32> value);
        partial void OnModifiedByChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTrainModel", Name="tblUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUser object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static tblUser CreatetblUser(global::System.Int32 userID)
        {
            tblUser tblUser = new tblUser();
            tblUser.UserID = userID;
            return tblUser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sex
        {
            get
            {
                return _Sex;
            }
            set
            {
                OnSexChanging(value);
                ReportPropertyChanging("Sex");
                _Sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sex");
                OnSexChanged();
            }
        }
        private Nullable<global::System.Int32> _Sex;
        partial void OnSexChanging(Nullable<global::System.Int32> value);
        partial void OnSexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Birthday
        {
            get
            {
                return _Birthday;
            }
            set
            {
                OnBirthdayChanging(value);
                ReportPropertyChanging("Birthday");
                _Birthday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Birthday");
                OnBirthdayChanged();
            }
        }
        private Nullable<global::System.DateTime> _Birthday;
        partial void OnBirthdayChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PermissionID
        {
            get
            {
                return _PermissionID;
            }
            set
            {
                OnPermissionIDChanging(value);
                ReportPropertyChanging("PermissionID");
                _PermissionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PermissionID");
                OnPermissionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PermissionID;
        partial void OnPermissionIDChanging(Nullable<global::System.Int32> value);
        partial void OnPermissionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Int32> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Int32> value);
        partial void OnIsActiveChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTrainModel", Name="ViewGetCurrentDate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ViewGetCurrentDate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ViewGetCurrentDate object.
        /// </summary>
        /// <param name="currentDateTime">Initial value of the CurrentDateTime property.</param>
        public static ViewGetCurrentDate CreateViewGetCurrentDate(global::System.DateTime currentDateTime)
        {
            ViewGetCurrentDate viewGetCurrentDate = new ViewGetCurrentDate();
            viewGetCurrentDate.CurrentDateTime = currentDateTime;
            return viewGetCurrentDate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CurrentDateTime
        {
            get
            {
                return _CurrentDateTime;
            }
            set
            {
                if (_CurrentDateTime != value)
                {
                    OnCurrentDateTimeChanging(value);
                    ReportPropertyChanging("CurrentDateTime");
                    _CurrentDateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CurrentDateTime");
                    OnCurrentDateTimeChanged();
                }
            }
        }
        private global::System.DateTime _CurrentDateTime;
        partial void OnCurrentDateTimeChanging(global::System.DateTime value);
        partial void OnCurrentDateTimeChanged();

        #endregion
    
    }

    #endregion
    
}
